Environment activated
/home/tsw96d/.conda/envs/YOLO/bin/python
Python 3.11.10
CUDA available: True
CUDA device count: 2
CUDA current device: 0
CUDA device name: Tesla V100-SXM2-32GB
Traceback (most recent call last):
  File "/home/tsw96d/YOLOComparision/YOLO_thermal_small/the-mill/scripts/small/YOLO9/train_YOLO9.py", line 4, in <module>
    model = YOLO("YOLO9s.yaml")
            ^^^^^^^^^^^^^^^^^^^
  File "/home/tsw96d/.conda/envs/YOLO/lib/python3.11/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/home/tsw96d/.conda/envs/YOLO/lib/python3.11/site-packages/ultralytics/engine/model.py", line 143, in __init__
    self._new(model, task=task, verbose=verbose)
  File "/home/tsw96d/.conda/envs/YOLO/lib/python3.11/site-packages/ultralytics/engine/model.py", line 248, in _new
    cfg_dict = yaml_model_load(cfg)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/tsw96d/.conda/envs/YOLO/lib/python3.11/site-packages/ultralytics/nn/tasks.py", line 1084, in yaml_model_load
    yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
                                                        ^^^^^^^^^^^^^^^^
  File "/home/tsw96d/.conda/envs/YOLO/lib/python3.11/site-packages/ultralytics/utils/checks.py", line 529, in check_yaml
    return check_file(file, suffix, hard=hard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsw96d/.conda/envs/YOLO/lib/python3.11/site-packages/ultralytics/utils/checks.py", line 521, in check_file
    raise FileNotFoundError(f"'{file}' does not exist")
FileNotFoundError: 'YOLO9s.yaml' does not exist
